window.SITE_CONTENT = window.SITE_CONTENT || {};

(function () {
  function esc(value) {
    return String(value).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  }

  function frame(caption, svg) {
    return '<figure class="diagram dsa-diagram">' + svg + '<figcaption>' + caption + '</figcaption></figure>';
  }

  function cells(values, options) {
    options = options || {};
    var width = 680, start = 32, cell = Math.min(94, (width - start * 2) / values.length);
    var row = values.map(function (value, i) {
      var active = options.active && options.active.indexOf(i) !== -1;
      var x = start + i * cell;
      return '<rect class="cell' + (active ? ' active' : '') + '" x="' + x + '" y="55" width="' + cell + '" height="48" rx="4"/>' +
        '<text x="' + (x + cell / 2) + '" y="84" text-anchor="middle">' + value + '</text>' +
        '<text class="muted" x="' + (x + cell / 2) + '" y="126" text-anchor="middle">' + i + '</text>';
    }).join('');
    var arrows = (options.pointers || []).map(function (p) {
      var x = start + p.index * cell + cell / 2;
      return '<path class="arrow" d="M ' + x + ' ' + (p.top ? 26 : 145) + ' L ' + x + ' ' + (p.top ? 48 : 110) + '"/>' +
        '<text class="label" x="' + x + '" y="' + (p.top ? 18 : 164) + '" text-anchor="middle">' + p.label + '</text>';
    }).join('');
    return frame(options.caption || 'The highlighted cells show the state the algorithm is currently reasoning about.', '<svg viewBox="0 0 680 180" role="img" aria-label="' + (options.aria || 'sequence diagram') + '">' + arrows + row + '</svg>');
  }

  function flow(nodes, caption, aria) {
    var width = 680, gap = 18, box = (width - 64 - gap * (nodes.length - 1)) / nodes.length;
    var pieces = nodes.map(function (node, i) {
      var x = 32 + i * (box + gap);
      var arrow = i < nodes.length - 1 ? '<path class="arrow" d="M ' + (x + box + 3) + ' 82 L ' + (x + box + gap - 5) + ' 82"/>' : '';
      return '<rect class="node' + (node.active ? ' active' : '') + '" x="' + x + '" y="55" width="' + box + '" height="54" rx="6"/>' +
        '<text x="' + (x + box / 2) + '" y="78" text-anchor="middle">' + node.top + '</text>' +
        '<text class="muted" x="' + (x + box / 2) + '" y="96" text-anchor="middle">' + node.bottom + '</text>' + arrow;
    }).join('');
    return frame(caption, '<svg viewBox="0 0 680 165" role="img" aria-label="' + aria + '">' + pieces + '</svg>');
  }

  function tree(caption, aria, labels) {
    labels = labels || ['8', '4', '12', '2', '6', '10', '14'];
    var points = [[340,30],[190,86],[490,86],[115,142],[265,142],[415,142],[565,142]];
    var edges = [[0,1],[0,2],[1,3],[1,4],[2,5],[2,6]].map(function (edge) {
      return '<line class="edge" x1="' + points[edge[0]][0] + '" y1="' + (points[edge[0]][1] + 20) + '" x2="' + points[edge[1]][0] + '" y2="' + (points[edge[1]][1] - 20) + '"/>';
    }).join('');
    var nodes = points.map(function (p, i) {
      return '<circle class="node' + (i === 0 ? ' active' : '') + '" cx="' + p[0] + '" cy="' + p[1] + '" r="20"/>' + '<text x="' + p[0] + '" y="' + (p[1] + 5) + '" text-anchor="middle">' + labels[i] + '</text>';
    }).join('');
    return frame(caption, '<svg viewBox="0 0 680 180" role="img" aria-label="' + aria + '">' + edges + nodes + '</svg>');
  }

  function grid(caption, aria) {
    var cellsOut = '', size = 52, originX = 210, originY = 24;
    for (var r = 0; r < 3; r++) for (var c = 0; c < 5; c++) {
      var cls = (r === 1 && c === 2) ? ' blocked' : (r === 0 && c === 0 ? ' active' : '');
      var label = r === 0 && c === 0 ? 'S' : (r === 2 && c === 4 ? 'T' : (r === 1 && c === 2 ? '×' : ''));
      cellsOut += '<rect class="cell' + cls + '" x="' + (originX + c * size) + '" y="' + (originY + r * size) + '" width="' + (size - 4) + '" height="' + (size - 4) + '" rx="4"/><text x="' + (originX + c * size + 24) + '" y="' + (originY + r * size + 31) + '" text-anchor="middle">' + label + '</text>';
    }
    return frame(caption, '<svg viewBox="0 0 680 190" role="img" aria-label="' + aria + '">' + cellsOut + '<path class="route" d="M 234 48 H 442 V 152"/><text class="muted" x="50" y="66">each cell is a node</text><text class="muted" x="50" y="92">4-direction moves are edges</text></svg>');
  }

  function dpTable(caption, aria, kind) {
    var rows = kind === 'knapsack' ? [['0','0','0','0','0','0'], ['2','0','0','3','3','3'], ['3','0','0','3','4','4']] : [['','0','1','2','3','4'], ['0','0','1','2','3','4'], ['1','1','1','2','3','4'], ['2','2','2','2','3','4'], ['3','3','3','3','3','4']];
    var startX = 150, startY = 26, w = 62, h = 30;
    var out = rows.map(function (row, r) { return row.map(function (value, c) {
      var active = (r === rows.length - 1 && c === row.length - 1) || (kind === 'knapsack' && r === 2 && c === 4);
      return '<rect class="cell' + (active ? ' active' : '') + '" x="' + (startX + c * w) + '" y="' + (startY + r * h) + '" width="' + (w - 3) + '" height="' + (h - 3) + '" rx="3"/><text x="' + (startX + c * w + 29) + '" y="' + (startY + r * h + 19) + '" text-anchor="middle">' + value + '</text>';
    }).join(''); }).join('');
    return frame(caption, '<svg viewBox="0 0 680 200" role="img" aria-label="' + aria + '"><text class="label" x="150" y="16">state table</text>' + out + '<path class="route" d="M 455 143 L 393 113 L 331 83"/></svg>');
  }

  function diagramFor(id) {
    var simple = {
      'what-an-algorithm-costs': frame('Growth changes the practical budget long before the code finishes.', '<svg viewBox="0 0 680 220" role="img" aria-label="complexity curves"><line class="edge" x1="65" y1="178" x2="640" y2="178"/><line class="edge" x1="65" y1="178" x2="65" y2="28"/><path class="curve linear" d="M 65 175 L 620 55"/><path class="curve quadratic" d="M 65 175 Q 330 165 430 40"/><path class="curve logarithmic" d="M 65 175 Q 240 110 620 85"/><text class="label" x="548" y="50">O(n²)</text><text class="label" x="585" y="82">O(n log n)</text><text class="label" x="590" y="112">O(n)</text><text class="muted" x="594" y="198">input size n</text></svg>'),
      'space-is-a-budget': flow([{top:'input',bottom:'O(n)'},{top:'two pointers',bottom:'O(1)',active:true},{top:'hash map',bottom:'O(n)'},{top:'recursion',bottom:'O(depth)'}], 'Different representations spend different amounts of memory.', 'space budget comparison'),
      'recursion-and-the-call-stack': flow([{top:'sum(0)',bottom:'waiting'},{top:'sum(1)',bottom:'waiting'},{top:'sum(2)',bottom:'base case',active:true},{top:'return',bottom:'unwind'}], 'Each recursive call waits on the smaller call below it.', 'recursion call stack'),
      'invariants-and-correctness': cells(['3','7','11','14','18','22','29'], { active:[2,3], pointers:[{label:'lo',index:2,top:true},{label:'hi',index:3,top:true}], aria:'binary search invariant range' }),
      'reading-constraints': flow([{top:'n ≤ 20',bottom:'search tree'},{top:'n ≤ 10⁵',bottom:'linear/logarithmic',active:true},{top:'small range',bottom:'counting'}], 'Input limits point toward a viable complexity class.', 'constraint to algorithm choice'),
      'arrays-and-locality': cells(['4','9','1','7','5','2'], { active:[3], pointers:[{label:'index 3',index:3,top:true}], aria:'array index access' }),
      'strings-as-arrays': cells(['r','a','c','e','c','a','r'], { active:[0,6], pointers:[{label:'left',index:0,top:true},{label:'right',index:6,top:true}], aria:'palindrome two pointers' }),
      'linked-lists-and-pointers': flow([{top:'head',bottom:'value 4'},{top:'next',bottom:'value 9',active:true},{top:'next',bottom:'value 1'},{top:'null',bottom:'end'}], 'A linked list changes local links instead of shifting a whole suffix.', 'linked list pointers'),
      'fast-and-slow-pointers': frame('The fast pointer gains one step per loop and eventually meets the slow pointer inside a cycle.', '<svg viewBox="0 0 680 190" role="img" aria-label="fast and slow cycle detection"><path class="edge" d="M 80 95 H 250 C 250 35 470 35 470 95 C 470 155 250 155 250 95"/><circle class="node" cx="80" cy="95" r="20"/><circle class="node active" cx="315" cy="46" r="20"/><circle class="node" cx="430" cy="145" r="20"/><text x="80" y="100" text-anchor="middle">slow</text><text x="315" y="51" text-anchor="middle">fast</text><text class="muted" x="530" y="93">cycle</text></svg>'),
      'stacks-and-monotonic-stacks': flow([{top:'5',bottom:'resolved'},{top:'3',bottom:'pop'},{top:'2',bottom:'stack',active:true},{top:'new 6',bottom:'arrives'}], 'A new value resolves only the stack entries it dominates.', 'monotonic stack resolution'),
      'queues-and-bfs': flow([{top:'start',bottom:'distance 0',active:true},{top:'neighbors',bottom:'distance 1'},{top:'next layer',bottom:'distance 2'}], 'A queue processes every node at one distance before moving farther away.', 'breadth first search queue'),
      'hash-maps-and-sets': frame('A hash map turns a value into a direct bucket lookup.', '<svg viewBox="0 0 680 175" role="img" aria-label="hash table buckets"><rect class="node" x="45" y="56" width="130" height="48" rx="6"/><text x="110" y="84" text-anchor="middle">key: 17</text><path class="arrow" d="M 180 80 H 300"/><rect class="node active" x="310" y="26" width="110" height="30" rx="4"/><rect class="node" x="310" y="66" width="110" height="30" rx="4"/><rect class="node" x="310" y="106" width="110" height="30" rx="4"/><text class="label" x="365" y="47" text-anchor="middle">bucket 1</text><text class="muted" x="455" y="84">expected O(1) lookup</text></svg>'),
      'trees-and-traversals': tree('Traversal order is a deliberate choice: node, left subtree, right subtree.', 'binary tree traversal'),
      'heaps-and-priority-queues': tree('The root is always the next minimum; the rest of the heap is only partially ordered.', 'min heap', ['1','3','5','8','7','9','6']),
      'tries-and-prefixes': tree('Shared prefixes share the same path, so lookup follows only the queried characters.', 'trie prefix path', ['a','p','p','l','e','y','?']),
      'two-pointers': cells(['1','3','4','7','9','12','15'], { active:[1,5], pointers:[{label:'left →',index:1,top:true},{label:'← right',index:5,top:true}], aria:'two pointers in sorted array' }),
      'sliding-window': cells(['a','b','c','a','b','b','c'], { active:[2,3,4,5], pointers:[{label:'left',index:2,top:true},{label:'right',index:5,top:true}], aria:'sliding window range' }),
      'binary-search': cells(['2','4','7','11','15','18','23'], { active:[3], pointers:[{label:'mid',index:3,top:true},{label:'search range',index:2,top:false}], aria:'binary search midpoint' }),
      'sorting-as-preprocessing': flow([{top:'[5,1]',bottom:'overlap'},{top:'[2,7]',bottom:'overlap',active:true},{top:'[8,9]',bottom:'new range'}], 'After sorting by start time, each interval only needs comparison with the active one.', 'sorted interval merge'),
      'divide-and-conquer': tree('Split the input until each piece is simple, then combine upward.', 'divide and conquer split', ['8 items','4','4','2','2','2','2']),
      'backtracking': tree('Each choice creates a branch; undoing state lets the next branch start clean.', 'backtracking decision tree', ['choose','take','skip','take','skip','take','skip']),
      'greedy-and-exchange': flow([{top:'finish 2',bottom:'take',active:true},{top:'finish 4',bottom:'compatible'},{top:'finish 8',bottom:'compatible'}], 'Taking the earliest finishing compatible interval leaves the most room for later choices.', 'greedy activity selection'),
      'prefix-sums': cells(['0','4','13','14','21','26'], { active:[2,4], pointers:[{label:'prefix[right + 1]',index:4,top:true},{label:'prefix[left]',index:2,top:true}], aria:'prefix sum range subtraction' }),
      'intervals': frame('Endpoint conventions decide whether touching intervals overlap.', '<svg viewBox="0 0 680 165" role="img" aria-label="interval endpoint conventions"><line class="edge" x1="110" y1="55" x2="570" y2="55"/><line class="edge" x1="110" y1="115" x2="570" y2="115"/><rect class="node active" x="180" y="40" width="180" height="30" rx="4"/><rect class="node" x="360" y="40" width="150" height="30" rx="4"/><text class="label" x="45" y="60">closed</text><rect class="node active" x="180" y="100" width="180" height="30" rx="4"/><rect class="node" x="360" y="100" width="150" height="30" rx="4"/><text class="label" x="35" y="120">half-open</text><text class="muted" x="535" y="60">touch = overlap</text><text class="muted" x="535" y="120">touch = separate</text></svg>'),
      'bitwise-tools': frame('One integer can hold a set when each bit names one member.', '<svg viewBox="0 0 680 170" role="img" aria-label="bit mask"><text class="label" x="105" y="45">bit</text><text class="label" x="105" y="100">mask</text><text x="200" y="45">7</text><text x="260" y="45">6</text><text x="320" y="45">5</text><text x="380" y="45">4</text><text x="440" y="45">3</text><text x="500" y="45">2</text><text x="560" y="45">1</text><text x="620" y="45">0</text><rect class="cell" x="174" y="66" width="55" height="48" rx="4"/><rect class="cell active" x="234" y="66" width="55" height="48" rx="4"/><rect class="cell" x="294" y="66" width="55" height="48" rx="4"/><rect class="cell active" x="354" y="66" width="55" height="48" rx="4"/><rect class="cell" x="414" y="66" width="55" height="48" rx="4"/><rect class="cell" x="474" y="66" width="55" height="48" rx="4"/><rect class="cell active" x="534" y="66" width="55" height="48" rx="4"/><rect class="cell" x="594" y="66" width="55" height="48" rx="4"/><text x="260" y="96" text-anchor="middle">1</text><text x="380" y="96" text-anchor="middle">1</text><text x="560" y="96" text-anchor="middle">1</text></svg>'),
      'modeling-a-graph': tree('An adjacency list stores only the relationships that actually exist.', 'graph adjacency relationship', ['A','B','C','D','E','F','G']),
      'dfs-and-components': tree('Depth-first search follows one branch until it must return.', 'depth first traversal tree', ['start','visit','later','deep','deep','deep','later']),
      'bfs-shortest-unweighted': flow([{top:'distance 0',bottom:'start',active:true},{top:'distance 1',bottom:'all neighbors'},{top:'distance 2',bottom:'next layer'}], 'BFS expands in layers, so the first visit has the fewest edges.', 'breadth first layers'),
      'topological-sort': flow([{top:'in-degree 0',bottom:'A',active:true},{top:'remove A',bottom:'unlocks B'},{top:'remove B',bottom:'unlocks C'}], 'Kahn’s algorithm emits a node only when no prerequisite remains.', 'topological sort dependencies'),
      'dijkstra': flow([{top:'distance 0',bottom:'settled',active:true},{top:'distance 4',bottom:'frontier'},{top:'distance 7',bottom:'tentative'}], 'The priority queue always expands the cheapest tentative route next.', 'Dijkstra priority queue'),
      'union-find': flow([{top:'1',bottom:'parent 1'},{top:'2',bottom:'parent 1',active:true},{top:'3',bottom:'parent 1'},{top:'find(3)',bottom:'root 1'}], 'Path compression points nodes directly toward the component representative.', 'union find parent links'),
      'minimum-spanning-tree': tree('Kruskal adds the next cheapest edge only when it joins separate components.', 'minimum spanning tree', ['A','B','C','D','E','F','G']),
      'grid-as-a-graph': grid('The grid becomes a graph when cells are nodes and legal moves are edges.', 'grid graph model'),
      'recognizing-dp': tree('Memoization turns repeated branches into one cached state.', 'overlapping dynamic programming subproblems', ['f(5)','f(4)','f(3)','f(3)','f(2)','f(2)','f(1)']),
      'state-transition-base': dpTable('Each state is filled from smaller states whose meaning is already known.', 'dynamic programming state transition'),
      'memoization-vs-tabulation': flow([{top:'recursive call',bottom:'memo lookup'},{top:'missing?',bottom:'compute',active:true},{top:'store state',bottom:'reuse later'}], 'Memoization computes states on demand; tabulation chooses an order up front.', 'memoization process'),
      'knapsack-and-subset': dpTable('A 0/1 knapsack state compares skipping an item with taking it.', 'knapsack dynamic programming table', 'knapsack'),
      'sequence-dp': dpTable('Each prefix state uses the diagonal or one of its neighboring prefix states.', 'sequence dynamic programming table'),
      'lis-and-patience': cells(['2','3','5','7','∞'], { active:[2], pointers:[{label:'replace first tail ≥ 5',index:2,top:true}], aria:'longest increasing subsequence tails' }),
      'interval-dp': frame('Interval DP fills short ranges before the larger ranges that depend on them.', '<svg viewBox="0 0 680 200" role="img" aria-label="interval dynamic programming order"><rect class="cell active" x="140" y="130" width="68" height="25" rx="4"/><rect class="cell active" x="215" y="130" width="68" height="25" rx="4"/><rect class="cell active" x="290" y="130" width="68" height="25" rx="4"/><rect class="cell active" x="365" y="130" width="68" height="25" rx="4"/><rect class="cell" x="178" y="92" width="106" height="25" rx="4"/><rect class="cell" x="253" y="92" width="106" height="25" rx="4"/><rect class="cell" x="328" y="92" width="106" height="25" rx="4"/><rect class="node active" x="215" y="50" width="181" height="26" rx="4"/><path class="arrow" d="M 250 88 L 185 120 M 326 88 L 326 120 M 400 88 L 400 120"/><text class="label" x="48" y="145">length 1</text><text class="label" x="48" y="108">length 2</text><text class="label" x="48" y="70">length 3</text></svg>'),
      'dp-space-optimization': flow([{top:'previous row',bottom:'keep',active:true},{top:'current row',bottom:'update'},{top:'older rows',bottom:'discard'}], 'When a transition reads only recent states, old rows can be discarded.', 'dynamic programming rolling rows'),
      'linked-list-variants': flow([{top:'singly',bottom:'next'},{top:'doubly',bottom:'prev + next',active:true},{top:'circular',bottom:'tail → head'}], 'List variants change the links each node stores and the operations they make direct.', 'linked list variants'),
      'stacks-and-queues': flow([{top:'stack',bottom:'LIFO'},{top:'push / pop',bottom:'one end',active:true},{top:'queue',bottom:'FIFO'},{top:'enqueue / dequeue',bottom:'two ends'}], 'A stack and a queue differ only in where insertion and removal happen.', 'stack and queue operations'),
      'deques-and-circular-buffers': frame('A circular buffer reuses array slots by wrapping the front and back indices.', '<svg viewBox="0 0 680 180" role="img" aria-label="circular buffer"><path class="edge" d="M 195 90 A 145 60 0 1 1 485 90 A 145 60 0 1 1 195 90"/><circle class="node active" cx="220" cy="90" r="22"/><circle class="node" cx="340" cy="32" r="22"/><circle class="node" cx="460" cy="90" r="22"/><text class="label" x="220" y="128" text-anchor="middle">front</text><text class="label" x="460" y="128" text-anchor="middle">back</text><text x="220" y="95" text-anchor="middle">0</text><text x="340" y="37" text-anchor="middle">1</text><text x="460" y="95" text-anchor="middle">2</text></svg>'),
      'binary-search-trees': tree('BST ordering places smaller keys on the left and larger keys on the right.', 'binary search tree ordering', ['8','4','12','2','6','10','14']),
      'self-balancing-trees': frame('A rotation restores balance while preserving the in-order key sequence.', '<svg viewBox="0 0 680 185" role="img" aria-label="binary tree rotation"><circle class="node active" cx="220" cy="45" r="20"/><circle class="node" cx="150" cy="120" r="20"/><circle class="node" cx="290" cy="120" r="20"/><line class="edge" x1="210" y1="62" x2="160" y2="102"/><line class="edge" x1="230" y1="62" x2="280" y2="102"/><path class="arrow" d="M 345 85 H 410"/><circle class="node active" cx="500" cy="45" r="20"/><circle class="node" cx="430" cy="120" r="20"/><circle class="node" cx="570" cy="120" r="20"/><line class="edge" x1="490" y1="62" x2="440" y2="102"/><line class="edge" x1="510" y1="62" x2="560" y2="102"/><text class="muted" x="220" y="174" text-anchor="middle">before</text><text class="muted" x="500" y="174" text-anchor="middle">after rotation</text></svg>'),
      'b-trees-and-b-plus-trees': flow([{top:'root page',bottom:'keys 20 | 50',active:true},{top:'internal page',bottom:'routing keys'},{top:'leaf pages',bottom:'linked records'}], 'B-trees keep many keys per node to reduce disk reads; B+ trees link their leaves for range scans.', 'B tree pages'),
      'fenwick-trees': frame('A Fenwick tree stores partial sums at indexes determined by each index’s lowest set bit.', '<svg viewBox="0 0 680 180" role="img" aria-label="Fenwick tree partial sums"><line class="edge" x1="160" y1="132" x2="280" y2="84"/><line class="edge" x1="280" y1="132" x2="280" y2="84"/><line class="edge" x1="400" y1="132" x2="520" y2="84"/><line class="edge" x1="520" y1="132" x2="520" y2="84"/><line class="edge" x1="280" y1="84" x2="400" y2="34"/><line class="edge" x1="520" y1="84" x2="400" y2="34"/><text x="160" y="150" text-anchor="middle">1</text><text x="280" y="150" text-anchor="middle">2</text><text x="400" y="150" text-anchor="middle">3</text><text x="520" y="150" text-anchor="middle">4</text><text class="label" x="400" y="24" text-anchor="middle">sum(1..4)</text></svg>'),
      'segment-trees': tree('A segment tree stores an aggregate for each interval, so range queries split into a few covered nodes.', 'segment tree intervals', ['[0,7]','[0,3]','[4,7]','[0,1]','[2,3]','[4,5]','[6,7]']),
      'sparse-tables': flow([{top:'length 1',bottom:'base values'},{top:'length 2',bottom:'min pairs'},{top:'length 4',bottom:'min blocks',active:true}], 'A sparse table precomputes powers-of-two ranges for fast immutable range queries.', 'sparse table levels'),
      'lru-cache': flow([{top:'hash map',bottom:'key → node'},{top:'head',bottom:'most recent',active:true},{top:'tail',bottom:'least recent'}], 'An LRU cache combines direct lookup with a doubly linked usage order.', 'LRU cache structure'),
      'skip-lists-and-bloom-filters': frame('A skip list adds express lanes; a Bloom filter trades false positives for compact membership checks.', '<svg viewBox="0 0 680 180" role="img" aria-label="skip list and bloom filter"><line class="edge" x1="70" y1="48" x2="355" y2="48"/><line class="edge" x1="70" y1="94" x2="580" y2="94"/><circle class="node" cx="70" cy="94" r="14"/><circle class="node active" cx="210" cy="94" r="14"/><circle class="node" cx="355" cy="94" r="14"/><circle class="node" cx="500" cy="94" r="14"/><circle class="node" cx="210" cy="48" r="14"/><circle class="node" cx="355" cy="48" r="14"/><text class="muted" x="65" y="145">skip-list express lane</text><rect class="cell active" x="445" y="128" width="24" height="24" rx="3"/><rect class="cell" x="474" y="128" width="24" height="24" rx="3"/><rect class="cell active" x="503" y="128" width="24" height="24" rx="3"/><text class="muted" x="540" y="146">Bloom bits</text></svg>')
    };
    return simple[id] || '';
  }

  /* A short, literal definition comes before the detailed explanation. The
     lessons remain technically precise, but a learner should not have to
     decode a dense first paragraph to know what the concept names. */
  var PLAIN_DEFINITIONS = {
    'what-an-algorithm-costs': 'A complexity class says how the amount of work grows when the input gets bigger. It is a scaling estimate, not a stopwatch reading.',
    'space-is-a-budget': 'Space complexity is the extra memory an algorithm needs while it runs, separate from the input and usually separate from the returned answer.',
    'recursion-and-the-call-stack': 'Recursion solves a problem by calling the same function on a smaller version until a base case stops the calls.',
    'invariants-and-correctness': 'A loop invariant is a fact that is true before the loop starts and stays true after every iteration. It is the reason the loop can be trusted.',
    'reading-constraints': 'Constraint analysis means using input limits, such as n = 200,000, to rule out algorithms that would take too long or use too much memory.',
    'arrays-and-locality': 'An array stores values next to each other, so an index is fast to read but inserting in the middle requires moving later values.',
    'strings-as-arrays': 'Most string algorithms treat text as an ordered sequence. The important detail is whether the language lets you change that sequence in place.',
    'linked-lists-and-pointers': 'A linked list stores each value in a separate node and connects nodes with links. You follow links instead of jumping to an index.',
    'fast-and-slow-pointers': 'Two pointers moving at different speeds can reveal a loop in a linked list or find its middle without storing visited nodes.',
    'stacks-and-monotonic-stacks': 'A monotonic stack keeps only unresolved values in increasing or decreasing order, so each new value can settle answers efficiently.',
    'queues-and-bfs': 'A queue removes the oldest item first. That order makes breadth-first search visit every location one step away before locations two steps away.',
    'hash-maps-and-sets': 'A hash set records whether a key exists. A hash map records a value for a key, such as a count or an earlier index.',
    'trees-and-traversals': 'A binary tree gives each node up to two children. A traversal is simply a rule for the order in which you visit those nodes.',
    'heaps-and-priority-queues': 'A heap keeps the smallest or largest item at the top without sorting every item. A priority queue exposes that top item repeatedly.',
    'tries-and-prefixes': 'A trie stores words by shared character prefixes, which makes prefix lookup direct but can use a lot of memory.',
    'linked-list-variants': 'Linked-list variants change which links each node stores: next only, previous plus next, or a tail that loops back to the head.',
    'stacks-and-queues': 'A stack removes the newest item first; a queue removes the oldest item first. That single ordering choice changes which problems they solve.',
    'deques-and-circular-buffers': 'A deque works at both ends. A circular buffer reuses a fixed array by wrapping its front and back positions around.',
    'binary-search-trees': 'A binary search tree places smaller keys on the left and larger keys on the right, so a comparison tells you which branch to follow.',
    'self-balancing-trees': 'A self-balancing search tree rearranges itself after changes so it does not become a long, slow chain.',
    'b-trees-and-b-plus-trees': 'B-trees keep many keys in each node so a search needs fewer disk or page reads. B+ trees keep actual records in linked leaf nodes.',
    'fenwick-trees': 'A Fenwick tree stores selected partial sums so you can update one value and ask for a prefix sum in logarithmic time.',
    'segment-trees': 'A segment tree stores an aggregate, such as a sum or minimum, for many nested ranges of an array.',
    'sparse-tables': 'A sparse table precomputes answers for fixed ranges whose lengths are powers of two. It is for data that will not change.',
    'lru-cache': 'An LRU cache removes the item that has gone unused for the longest time while keeping lookup and recency updates fast.',
    'skip-lists-and-bloom-filters': 'A skip list uses extra shortcut links to search quickly. A Bloom filter is a compact membership test that may say yes incorrectly but never says no incorrectly.',
    'two-pointers': 'Two pointers keep two positions in the same sequence and move one or both based on a rule that makes discarded positions impossible answers.',
    'sliding-window': 'A sliding window represents one continuous part of an array or string and moves its left and right edges instead of rebuilding that part each time.',
    'binary-search': 'Binary search repeatedly cuts an ordered search space in half. It works when each comparison tells you which half cannot contain the answer.',
    'sorting-as-preprocessing': 'Sorting puts related values next to each other or in a useful order, so a single scan can replace many pairwise comparisons.',
    'divide-and-conquer': 'Divide and conquer splits a problem into smaller independent parts, solves them, then combines their results.',
    'backtracking': 'Backtracking tries a choice, explores its consequences, undoes that choice, and then tries the next option.',
    'greedy-and-exchange': 'A greedy algorithm makes the best-looking local choice now. It is correct only when you can prove that choice never blocks an optimal final answer.',
    'prefix-sums': 'A prefix-sum array stores the total up to every position, so any fixed range sum becomes one subtraction.',
    'intervals': 'An interval is a range with a start and an end. Before writing code, decide whether endpoints that touch count as overlapping.',
    'bitwise-tools': 'Bit operations work on the individual 0 and 1 digits of an integer. A bitmask can represent a small set using one number.',
    'modeling-a-graph': 'A graph represents things as vertices and their relationships as edges. Choosing directed, undirected, weighted, or unweighted edges is part of the solution.',
    'dfs-and-components': 'Depth-first search follows one path as far as it can before returning. Repeating it from unseen nodes finds separate connected groups.',
    'bfs-shortest-unweighted': 'Breadth-first search explores in layers. In an unweighted graph, the first time it reaches a node is through the fewest edges.',
    'topological-sort': 'A topological order lists prerequisites before the work that depends on them. It exists only when a directed graph has no cycle.',
    'dijkstra': 'Dijkstra’s algorithm finds cheapest paths by always processing the not-yet-final route with the smallest known cost.',
    'union-find': 'Disjoint Set Union keeps track of which items belong to the same group as groups are merged over time.',
    'minimum-spanning-tree': 'A minimum spanning tree connects every vertex with the least total edge weight, without requiring shortest routes from one vertex.',
    'grid-as-a-graph': 'A grid becomes a graph when each usable cell is a vertex and each legal move to a neighbor is an edge.',
    'recognizing-dp': 'Dynamic programming saves the answer for each repeated subproblem, so the program solves each distinct state once instead of many times.',
    'state-transition-base': 'A DP state says exactly what one table entry means. A transition explains how smaller entries produce it, and base cases start the process.',
    'memoization-vs-tabulation': 'Memoization fills states when recursive calls ask for them. Tabulation fills states in a planned order, usually with loops.',
    'knapsack-and-subset': '0/1 knapsack chooses whether to take each item once while staying within a capacity limit and maximizing total value.',
    'sequence-dp': 'Sequence DP compares prefixes of one or two ordered sequences, such as the first i characters of one string and first j of another.',
    'lis-and-patience': 'The longest increasing subsequence is the longest ordered set of values that increases, even when its values are not adjacent in the input.',
    'interval-dp': 'Interval DP stores an answer for every subrange and builds larger ranges from smaller ranges inside them.',
    'dp-space-optimization': 'DP space optimization keeps only the earlier states that the next computation still needs, instead of retaining the whole table.'
  };

  /* The first explanation is deliberately conversational and procedural.
     The original precise explanation remains available as implementation
     detail for learners who are ready for the formal version. */
  var PLAIN_SOLUTIONS = {
    'what-an-algorithm-costs': 'First ask how many times the code can repeat as n grows. Keep the term that grows fastest: a loop over n items is O(n); two full nested loops are usually O(n²).',
    'space-is-a-budget': 'List every structure created while the algorithm runs. If it grows with the input, include it. Two index variables stay O(1); a map that can hold every item is O(n).',
    'recursion-and-the-call-stack': 'Make each call smaller, and stop at a simple base case. Trust the smaller call to return the right answer, then combine that answer with the current piece of work.',
    'invariants-and-correctness': 'Before the loop, write one sentence about what the variables mean. After each update, check that the sentence is still true. At the end, use that sentence to justify the answer.',
    'reading-constraints': 'Read n before choosing an algorithm. Estimate the work: for n near 100,000, avoid checking every pair; for n near 20, trying every subset may be acceptable.',
    'arrays-and-locality': 'Use an array when you need quick access by position. Append at the end when possible. Expect a cost when inserting or deleting near the front because later values must shift.',
    'strings-as-arrays': 'Walk through text with indexes when you need to compare characters. Build new text in an array or buffer when many changes are needed, then join it once.',
    'linked-lists-and-pointers': 'Use a list when you already have the node before the change. Save the next link before changing any pointer, then reconnect the two affected nodes.',
    'fast-and-slow-pointers': 'Move slow by one link and fast by two. If fast reaches the end, there is no loop. If they meet, there is a loop because fast gains one step each round.',
    'stacks-and-monotonic-stacks': 'Keep indexes whose answer is still unknown. When a new value arrives, pop every index that the new value answers, record the answer, then push the new index.',
    'queues-and-bfs': 'Put the start node in a queue. Take one node from the front, add each unseen neighbor to the back, and mark it seen immediately. This naturally visits nodes by distance.',
    'hash-maps-and-sets': 'For each item, store the one fact you will need later: whether it was seen, how many times it appeared, or where it appeared. Look up that fact instead of scanning earlier items.',
    'trees-and-traversals': 'For every node, decide what to do before its children, between its children, or after its children. Return a simple value for an empty child so parent calls can combine child results.',
    'heaps-and-priority-queues': 'Put items in a min-heap when you repeatedly need the smallest item, or a max-heap for the largest. Remove the top only when you need it; do not sort the whole collection after every change.',
    'tries-and-prefixes': 'Follow one child per character. Create a child when inserting a new word, and mark the final node as a complete word. A prefix is present if its path exists.',
    'linked-list-variants': 'Choose singly linked for simple forward movement, doubly linked when you must remove a known node, and circular when work should continue from the end back to the start.',
    'stacks-and-queues': 'Use a stack when the newest unfinished task must be handled next. Use a queue when the oldest waiting task must be handled next. Pick the removal order before writing code.',
    'deques-and-circular-buffers': 'Use a deque when both ends matter. For a fixed-size queue, store front and back indexes and move an index back to zero after it reaches the last array slot.',
    'binary-search-trees': 'Compare the target with the current node. Go left for a smaller target and right for a larger target. Stop when you find it or reach an empty child.',
    'self-balancing-trees': 'After inserting or removing a key, check whether one side became much taller. Rotate a small part of the tree to shorten the tall side without changing the sorted order.',
    'b-trees-and-b-plus-trees': 'Store many sorted keys in one node or page. Search inside that page, then follow one child page. Keeping more keys per page reduces slow storage reads.',
    'fenwick-trees': 'Use the low bit of an index to jump across grouped sums. Update the few group totals that contain one position; query the few group totals that cover a prefix.',
    'segment-trees': 'Build a tree where each node stores the answer for one range. For a query, combine only nodes that exactly cover pieces of the requested range. Update the path from one changed value to the root.',
    'sparse-tables': 'Precompute answers for ranges of length 1, 2, 4, and so on. Answer a static range query by combining one or two precomputed blocks.',
    'lru-cache': 'Use a map to find a cached key immediately and a doubly linked list to move that key to the most-recent end. When full, remove the node at the least-recent end.',
    'skip-lists-and-bloom-filters': 'Use a skip list when random shortcut links are acceptable for fast ordered lookup. Use a Bloom filter only as a cheap first check: “not present” is certain, “present” needs verification.',
    'two-pointers': 'Set two indexes, then move exactly one according to a rule. In a sorted two-sum problem, a sum that is too small means move left; a sum that is too large means move right.',
    'sliding-window': 'Move the right edge to include a new item. If the window becomes invalid, move the left edge until it is valid again. Update the answer at the point the problem asks for it.',
    'binary-search': 'Keep a range that still might contain the answer. Inspect the middle. Throw away the half that cannot work, and repeat until the range is empty or one answer remains.',
    'sorting-as-preprocessing': 'Sort first when order makes comparisons local. Then scan from left to right, comparing the current item with the small amount of state you carried from earlier items.',
    'divide-and-conquer': 'Split the input into smaller parts until each part is easy. Solve those parts, then do one controlled combine step. Make sure every split is strictly smaller than the original.',
    'backtracking': 'Choose one option, update the current path, and recurse. When that branch returns, undo exactly that update before trying the next option. Stop early when a partial path cannot succeed.',
    'greedy-and-exchange': 'Choose the locally best option only after you can explain why an optimal answer can be changed to include it. If you cannot make that exchange argument, look for DP or search instead.',
    'prefix-sums': 'Build one running-total array once. To get the sum from left through right, subtract the total before left from the total through right.',
    'intervals': 'Sort intervals by start. Keep one active interval. If the next interval overlaps under your endpoint rule, merge or count it; otherwise start a new active interval.',
    'bitwise-tools': 'Think of each bit position as one yes/no flag. Use AND to test a flag, OR to set it, XOR to flip it, and shifts to move between bit positions.',
    'modeling-a-graph': 'Name what counts as a node and what counts as a connection. Then write an adjacency list, add both directions for an undirected relationship, and attach weights only when costs differ.',
    'dfs-and-components': 'Start at one unseen node, mark it seen, and keep following an unseen neighbor until no path remains. Repeat from another unseen node to find another component.',
    'bfs-shortest-unweighted': 'Start with distance zero. When you add a neighbor to the queue, assign it the current distance plus one. The first assignment is the fewest-edge distance.',
    'topological-sort': 'Count each node’s remaining prerequisites. Start with nodes that have zero. Remove one, reduce the counts of tasks it unlocks, and enqueue tasks whose count becomes zero.',
    'dijkstra': 'Start with distance zero at the source. Always take the currently cheapest unfinished route from a min-heap, then try to improve each neighbor’s distance through that route.',
    'union-find': 'Give every item a parent. To check whether two items are connected, follow parents to their roots. To merge groups, point one root at the other and compress paths as you go.',
    'minimum-spanning-tree': 'Sort edges from cheapest to most expensive. Add an edge only if it connects two different groups. Stop after connecting every vertex; Union-Find tells you whether an edge would make a cycle.',
    'grid-as-a-graph': 'For each cell, try the allowed direction offsets. Ignore out-of-bounds and blocked cells. Then use DFS for regions or BFS for the fewest number of moves.',
    'recognizing-dp': 'Write the recursive answer first. When the same arguments appear again, save the result and reuse it. The saved arguments are the DP state.',
    'state-transition-base': 'Write a full sentence for one table entry. List the smaller entries that can lead to it. Set the simplest entries by hand first, then fill the rest in dependency order.',
    'memoization-vs-tabulation': 'Use memoization when the recursive version is easy to write and many states may never be reached. Use tabulation when you know a safe order and want to avoid call-stack depth.',
    'knapsack-and-subset': 'For each item and each capacity, compare skipping the item with taking it. In a one-row version, walk capacity backward so one item cannot be used twice in the same pass.',
    'sequence-dp': 'Let row i and column j describe prefixes. When the current characters match, use the diagonal result; otherwise choose the better result after skipping one character from one side.',
    'lis-and-patience': 'Keep the smallest tail value seen for every possible subsequence length. For each number, replace the first tail that is at least that number, or append a new tail.',
    'interval-dp': 'Start with the shortest ranges. For each larger range, try every possible final split or final action, using answers that were already computed for the smaller inside ranges.',
    'dp-space-optimization': 'Look at which earlier table entries one new entry reads. Keep only those rows or variables, but do not overwrite an old value before every later calculation that needs it.'
  };

  function lesson(id, title, problem, solution, limitation, gotcha, example) {
    var definition = PLAIN_DEFINITIONS[id] || '';
    var plainSolution = PLAIN_SOLUTIONS[id] || solution;
    var body = '<div class="plain-definition"><span class="label">In plain words</span><p>' + definition + '</p></div>';
    body += '<div class="beat problem"><span class="label">Problem</span><p>' + problem + '</p></div>';
    body += '<div class="beat solution"><span class="label">Solution</span><p>' + plainSolution + '</p>';
    body += '<details class="implementation"><summary>Implementation detail</summary><p>' + solution + '</p></details>';
    if (example) body += '<pre><code>' + esc(example) + '</code></pre>';
    body += '</div>';
    body += diagramFor(id);
    body += '<div class="beat limitation"><span class="label">Limitation</span><p>' + limitation + '</p></div>';
    body += '<div class="gotcha"><span class="label">Gotcha</span><p>' + gotcha + '</p></div>';
    return { id: id, title: title, body: body };
  }

  function track(name, steps) { return { track: name, steps: steps }; }

  window.SITE_CONTENT["foundations"] = track("1. Foundations", [
    lesson("what-an-algorithm-costs", "Asymptotic Complexity", "Two programs can return the same answer while one finishes before the other has read its input. Without a cost model, 'fast' is just a feeling.", "Count how work grows as input size n grows. Big-O gives an upper growth bound, Big-Theta a tight growth class, and Big-Omega a lower bound. Ignore constants only after identifying the dominant term.", "Asymptotic notation does not measure network delays, cache effects, allocation cost, or the constant factors that can dominate small inputs.", "O(n log n) is not automatically faster than O(n): benchmark when constraints are small, but use growth analysis to rule out approaches that cannot scale.", "n = 1_000_000\nO(n)      ≈ 1,000,000 units\nO(n log n)≈ 20,000,000 units\nO(n²)      ≈ 1,000,000,000,000 units"),
    lesson("space-is-a-budget", "Space Complexity", "An approach can be fast and still fail because it keeps a second copy of the input, a huge visited set, or a recursion stack that exhausts memory.", "Track auxiliary space separately from the input. An in-place transformation uses O(1) extra space; a hash map keyed by every element uses O(n); a recursion depth d consumes O(d) call-stack frames.", "Some problems require remembering information. You cannot reconstruct arbitrary past values without storage, and time-space tradeoffs are often real rather than implementation mistakes.", "Do not call an algorithm O(1) space merely because its output is excluded. Be explicit: auxiliary space versus output space.", "// Two pointers: O(1) extra space\nlet left = 0, right = values.length - 1;\nwhile (left < right) { /* inspect and move pointers */ }"),
    lesson("recursion-and-the-call-stack", "Recursion", "Many structures are naturally recursive: a tree contains subtrees, a divide-and-conquer problem contains smaller versions of itself. Iteration can hide that shape.", "Write a base case that stops, a smaller subproblem, and a rule that combines its answer. Each call owns its local variables until it returns, which is why recursive code has a call stack.", "Every recursive call has overhead and depth is bounded by the runtime stack. A skewed tree can turn a logically clean O(n) traversal into a stack overflow.", "A recursive function is not correct because it looks elegant. Prove that each call makes progress toward a base case and that the combine step preserves the desired invariant.", "function sum(a, i = 0) {\n  if (i === a.length) return 0;\n  return a[i] + sum(a, i + 1);\n}"),
    lesson("invariants-and-correctness", "Loop Invariants", "A test suite samples inputs; it cannot prove every unseen case. You need a statement that remains true after each iteration or recursive step.", "Name the invariant before writing the loop. For binary search: the answer, if present, remains inside the current inclusive range. For a monotonic stack: values are ordered from bottom to top.", "An invariant proves only what it states. You still need initialization, preservation, and termination to connect it to the final answer.", "If you cannot say what your pointers or data structure represent at each line, edge cases will feel mysterious because the code has no stable meaning.", "// invariant: all indices < write contain non-zero values\nlet write = 0;\nfor (const x of nums) if (x !== 0) nums[write++] = x;"),
    lesson("reading-constraints", "Constraint Analysis", "A problem statement often tells you the intended complexity without naming the technique. Ignoring n leads to perfectly correct code that times out.", "Translate limits into a budget: n around 10^5 usually permits O(n) or O(n log n); n around 20 may permit O(2^n); a tiny value range may unlock counting. Then choose a representation that supports the required operations.", "These are heuristics, not laws. Input distribution, number of test cases, and language overhead matter.", "Always ask whether the data is sorted, mutable, unique, bounded, or streamed. Those facts often matter more than the story wrapped around the problem.", "n ≤ 2 × 10^5  → avoid O(n²)\nn ≤ 20         → subset/backtracking may fit\nvalue range ≤ n → counting or frequency array may fit")
  ]);

  window.SITE_CONTENT["structures"] = track("2. Core Data Structures", [
    lesson("arrays-and-locality", "Arrays", "You need to read the 50,000th item immediately, but you also sometimes need to insert at the front. Those operations pull in opposite directions.", "An array stores elements contiguously, so index i is O(1). Appending is amortized O(1) for dynamic arrays; inserting or deleting in the middle shifts a suffix and costs O(n).", "Growing an array occasionally reallocates and copies everything. The average append cost is still O(1), not worst-case O(1).", "'Array lookup is O(1)' means lookup by index. Searching for a value in an unsorted array is O(n).", "index:  0   1   2   3\narray: [4,  9,  1,  7]\naddress(i) = base + i × elementSize"),
    lesson("strings-as-arrays", "Strings", "Text problems look like character problems, but repeatedly joining immutable strings can copy the whole prefix over and over.", "Treat a string as a sequence. Use two pointers for palindromes, a frequency table for bounded alphabets, and a mutable buffer or array when constructing output incrementally.", "Unicode complicates 'character': code units, code points, and grapheme clusters are not identical in every language.", "Before using a 26-slot frequency array, verify the input is lowercase English letters. Otherwise use a map or normalize deliberately.", "// palindrome after normalization\nwhile (left < right) {\n  if (text[left++] !== text[right--]) return false;\n}\nreturn true;"),
    lesson("linked-lists-and-pointers", "Linked Lists", "An array makes random access trivial but moving a large suffix is expensive. A list makes local edits cheap if you already know the location.", "Each node stores a value and a next pointer. Insert or delete after a known node by rewiring O(1) pointers; reach the k-th node by walking O(k) links.", "Nodes add pointer overhead and tend to have poor cache locality. In ordinary application code, dynamic arrays often win despite their asymptotic insertion cost.", "A dummy head removes special cases at the real head. It is a reasoning tool, not a hack.", "let prev = null, cur = head;\nwhile (cur) {\n  const next = cur.next; cur.next = prev;\n  prev = cur; cur = next;\n}\nreturn prev;"),
    lesson("fast-and-slow-pointers", "Fast and Slow Pointers", "A linked list may contain a cycle, yet the list gives you no indices and you cannot safely keep walking forever.", "Advance one pointer one step and another two. If a cycle exists, their relative speed makes them meet; if fast reaches null, the list ends. Resetting one pointer can then locate the cycle entry.", "This pattern relies on deterministic next links. It does not replace a visited set in a general graph where a node can have many neighbors.", "For the middle of a list, decide which middle you want on even lengths before choosing loop conditions.", "while (fast && fast.next) {\n  slow = slow.next;\n  fast = fast.next.next;\n  if (slow === fast) return true;\n}\nreturn false;"),
    lesson("stacks-and-monotonic-stacks", "Monotonic Stacks", "'Next greater value to the right' looks like a nested-loop problem because the answer lies in the future.", "Keep unresolved indices on a stack. When a new value arrives, it resolves every smaller value on a decreasing stack. Each item enters and leaves once, so the total work is O(n).", "The stack order must match the question: decreasing for next greater, increasing for next smaller. Store indices when distances or answer positions matter.", "Do not confuse a monotonic stack with a sorted stack. It contains only unresolved candidates, not every item in sorted order.", "for (let i = 0; i < a.length; i++) {\n  while (stack.length && a[stack.at(-1)] < a[i]) {\n    answer[stack.pop()] = i;\n  }\n  stack.push(i);\n}"),
    lesson("queues-and-bfs", "Queues and Breadth-First Search", "When every move has equal cost, the first time you reach a state should be the cheapest. A stack would explore one deep branch before nearby states.", "A queue is FIFO: enqueue at the back, dequeue at the front. Breadth-first search processes distance 0, then 1, then 2, so it finds shortest unweighted paths.", "Using shift() on a JavaScript array can be O(n). Use a head index or a deque implementation for large queues.", "Mark a graph node visited when enqueuing, not when dequeuing, to avoid inserting the same node many times.", "const queue = [start]; let head = 0; seen.add(start);\nwhile (head < queue.length) {\n  const node = queue[head++];\n  for (const next of graph[node]) if (!seen.has(next)) {\n    seen.add(next); queue.push(next);\n  }\n}"),
    lesson("hash-maps-and-sets", "Hash Tables", "Repeatedly asking 'have I seen this value?' by scanning a prefix turns a simple pass into O(n²).", "A hash table maps a key to a bucket, giving expected O(1) insert, lookup, and delete. A set stores membership; a map associates a value such as a prior index or count.", "Worst-case behavior can degrade with collisions, and hash iteration order is not a substitute for sorted order.", "The key is the algorithmic decision: store exactly the information a future step needs. A map of every detail is not automatically useful.", "const firstIndex = new Map();\nfor (let i = 0; i < nums.length; i++) {\n  const need = target - nums[i];\n  if (firstIndex.has(need)) return [firstIndex.get(need), i];\n  firstIndex.set(nums[i], i);\n}"),
    lesson("trees-and-traversals", "Binary Trees and Traversals", "A tree is not inherently sorted or searchable. Traversal order changes the meaning of the result.", "Preorder visits node-left-right, inorder visits left-node-right, postorder visits left-right-node, and level order uses a queue. Inorder is sorted only when the tree is a valid BST.", "Recursive traversal uses height-sized stack space. A pathological tree has height O(n), not O(log n).", "For tree recursion, define what the function returns for a null child. That base result is usually the key to combining children correctly.", "function height(node) {\n  if (!node) return 0;\n  return 1 + Math.max(height(node.left), height(node.right));\n}"),
    lesson("heaps-and-priority-queues", "Heaps and Priority Queues", "You need repeated access to the smallest or largest item, but sorting after every insertion wastes work.", "A binary heap is a complete tree stored in an array. Its root is the min or max in O(1); insert and remove-root repair one path in O(log n).", "A heap is not fully sorted. Searching for an arbitrary value is O(n), and iterating it does not produce sorted order.", "For top-k problems, maintain a heap of size k: the root is the current boundary, giving O(n log k) instead of sorting all n values.", "parent(i) = floor((i - 1) / 2)\nleft(i)   = 2i + 1\nright(i)  = 2i + 2"),
    lesson("tries-and-prefixes", "Tries", "A hash set answers whether a whole word exists, but autocomplete asks whether any stored word begins with a prefix.", "A trie stores one character per edge. Following a prefix costs O(length of prefix), independent of how many words were inserted. A terminal flag distinguishes a word from a mere prefix.", "A sparse trie can use substantial memory because every node needs child references. A sorted list plus binary search can be simpler for static data.", "Do not count a path as a word unless its terminal marker is set: 'app' and 'apple' can share the same path.", "root\n └─ a ─ p ─ p* ─ l ─ e*\n          word   word")
  ]);

  window.SITE_CONTENT["advanced-structures"] = track("3. Advanced Data Structures", [
    lesson("linked-list-variants", "Linked List Variants", "A singly linked list makes forward traversal simple, but some operations need a predecessor or need to wrap from the last node back to the first.", "A doubly linked list stores both prev and next pointers, allowing O(1) removal of a known node. A circular linked list makes tail.next point to head, which is useful for round-robin scheduling.", "Extra links consume memory and add invariants that each mutation must preserve. A dynamic array is often a better default when random access or cache locality matters.", "When removing a doubly linked node, update both neighboring links. Updating only one direction leaves a structure that looks valid from one end and corrupt from the other.", "singly: head → A → B → null\ndoubly: null ← A ⇄ B ⇄ C → null\ncircular: A → B → C ─┐\n          └───────────┘"),
    lesson("stacks-and-queues", "Stacks and Queues", "Many algorithms need controlled access to recent or pending work. A plain array does not state whether the next item should be the newest or oldest.", "A stack provides LIFO operations through push and pop. A queue provides FIFO operations through enqueue and dequeue. Both can be implemented in O(1) per operation with the correct underlying representation.", "A stack cannot provide shortest-path layers by itself, and a queue cannot model nested scopes or undo history by itself. The removal rule determines the algorithm.", "In JavaScript, repeatedly calling shift() is not an O(1) queue. Keep a head index or use a deque implementation.", "stack: push → [A, B, C] → pop C\nqueue: enqueue → [A, B, C] → dequeue A"),
    lesson("deques-and-circular-buffers", "Deques and Circular Buffers", "Some problems need O(1) insertion and removal at both ends: sliding-window maxima, work stealing, and bounded streaming buffers.", "A deque supports front and back operations. A circular buffer uses a fixed array plus wrapping indexes, reusing freed cells without shifting values. A monotonic deque combines this with an ordering invariant.", "A circular buffer has a fixed capacity unless it resizes. You must decide whether a full buffer rejects, overwrites, or grows before implementing it.", "Use a count or reserve one empty slot to distinguish empty from full when front and back indexes are equal.", "next(i) = (i + 1) % capacity\nempty: count === 0\nfull:  count === capacity"),
    lesson("binary-search-trees", "Binary Search Trees", "A binary tree gives hierarchy but no fast value lookup unless it enforces an ordering rule.", "A binary search tree keeps smaller keys in the left subtree and larger keys in the right subtree. Search, insertion, deletion, predecessor, successor, and ordered range operations follow one root-to-leaf path when height is logarithmic.", "A BST can become a chain after sorted insertion, making its operations O(n). The ordering rule alone does not guarantee balance.", "For deletion of a node with two children, replace it with its inorder successor or predecessor, then delete that replacement node from its original position.", "search(key): compare at each node\nkey < node.key → left\nkey > node.key → right"),
    lesson("self-balancing-trees", "Self-Balancing Binary Search Trees", "A BST with a bad insertion order loses the logarithmic height that makes it useful.", "AVL trees maintain tight height balance using rotations. Red-black trees maintain color rules that bound height while allowing fewer rotations. Both keep lookup, insertion, and deletion O(log n).", "These structures are complex to implement correctly. Standard-library ordered maps and sets are usually safer than writing one from scratch.", "Rotations change links but must preserve in-order key order. Test parent pointers and subtree roots after every rotation case.", "AVL: stricter height balance\nRed-black: fewer rotations, common in ordered maps"),
    lesson("b-trees-and-b-plus-trees", "B-Trees and B+ Trees", "Binary trees waste disk reads when every node access fetches a whole storage page but stores only one or two useful keys.", "B-trees store many sorted keys and child pointers per node, keeping height small. B+ trees keep records in linked leaves, which makes range scans efficient. Databases and file systems use these ideas for page-oriented storage.", "The optimal node size depends on page size and workload. These structures solve external-memory problems more than small in-memory interview problems.", "In a B+ tree, internal nodes guide the search while leaves contain the ordered records; do not treat it as simply a wider binary tree.", "root page → internal pages → linked leaf pages"),
    lesson("fenwick-trees", "Fenwick Trees", "Prefix sums answer range sums quickly only while the underlying array is fixed. Updating a value would require recomputing a long suffix.", "A Fenwick tree stores selected partial sums in an array. Point updates and prefix sums both take O(log n); a range sum is two prefix sums. The lowest set bit chooses the covered block at each index.", "Fenwick trees are specialized: they work best for associative prefix aggregates with inverse or subtraction support. They are less flexible than segment trees.", "Use one-based indexing. At index zero, index += index & -index never advances.", "update(i, delta): i += i & -i\nprefix(i):        i -= i & -i"),
    lesson("segment-trees", "Segment Trees", "You need updates and range minimum, maximum, or sum queries. Prefix sums cannot update efficiently, and a single heap cannot answer arbitrary ranges.", "A segment tree stores an aggregate for each interval. A query visits only nodes whose intervals cover the requested range; point updates repair the path to the root. Both operations are O(log n).", "It uses more memory and code than a Fenwick tree. Lazy propagation adds range updates but substantially increases implementation complexity.", "Define the identity value for an empty range: 0 for sum, positive infinity for minimum, and negative infinity for maximum.", "node [l,r]\n├─ [l,mid]\n└─ [mid+1,r]"),
    lesson("sparse-tables", "Sparse Tables", "Range minimum queries over immutable data can be asked many times, making an O(log n) segment-tree query unnecessary overhead.", "A sparse table precomputes aggregates for ranges of length 2^k. Idempotent operations such as min, max, and gcd answer a query in O(1) from two overlapping blocks after O(n log n) preprocessing.", "It is not suitable for frequent updates because changing one value invalidates many precomputed blocks.", "The overlapping-block O(1) trick depends on idempotence. It does not work for sums because adding an overlap twice changes the result.", "query [l,r]: k = floor(log2(r-l+1))\nmin(table[k][l], table[k][r-2^k+1])"),
    lesson("lru-cache", "LRU Cache", "A cache must find a key instantly and also evict the least recently used key instantly when capacity is full.", "Combine a hash map from key to node with a doubly linked list ordered by recency. Lookup finds the node in O(1); moving it to the head and removing the tail are O(1).", "An LRU policy is not always the best eviction policy. It can retain items that were recently scanned once and discard items with a predictable reuse pattern.", "Updating an existing key must move its node to most-recent position; otherwise the cache returns correct values but evicts the wrong entry.", "map: key → list node\nhead: most recent\ntail: least recent"),
    lesson("skip-lists-and-bloom-filters", "Skip Lists and Bloom Filters", "Some systems need fast ordered operations with simpler probabilistic balancing, or extremely compact membership tests where an occasional false positive is acceptable.", "A skip list adds randomized higher-level forward links and has expected O(log n) search and update. A Bloom filter hashes an item into several bits and gives no false negatives, but can give false positives.", "Skip-list performance is expected rather than deterministic. A Bloom filter cannot retrieve values or reliably prove a value is absent only when it says possibly present.", "A Bloom filter that says 'not present' is definitive; one that says 'present' must be verified against the source of truth.", "skip list: randomized express lanes\nBloom filter: k hashes → bit array")
  ]);

  window.SITE_CONTENT["patterns"] = track("4. Algorithm Patterns", [
    lesson("two-pointers", "Two Pointers", "Comparing every pair costs O(n²), but a sorted sequence gives each comparison directional meaning.", "Put one pointer at each end. If the sum is too small, move left; if too large, move right. The invariant is that discarded pairs cannot be answers, so each pointer moves at most n times.", "The direction rule depends on sorted order or another monotonic property. On arbitrary input, sort a copy or use hashing when original indices matter.", "Do not move both pointers after one mismatch unless your invariant proves both discarded regions are impossible.", "while (left < right) {\n  const sum = a[left] + a[right];\n  if (sum === target) return [left, right];\n  if (sum < target) left++; else right--;\n}"),
    lesson("sliding-window", "Sliding Window", "Many subarray and substring questions ask for the best contiguous region. Recomputing each region from scratch repeats nearly all work.", "Maintain a window [left, right] and the smallest state needed to judge it: a sum, frequency map, or count. Expand right; while the window violates the condition, advance left and update state.", "Sliding window needs a way to repair invalidity by moving left. Negative values can break sum-based monotonic reasoning.", "Write down precisely what makes a window valid and when its answer should be recorded: before or after shrinking changes the result.", "for (let right = 0; right < s.length; right++) {\n  add(s[right]);\n  while (!valid()) remove(s[left++]);\n  best = Math.max(best, right - left + 1);\n}"),
    lesson("binary-search", "Binary Search", "Halving an array is familiar, but off-by-one errors happen because code moves pointers without stating what each bound means.", "Use binary search whenever a predicate is monotonic: false, false, false, true, true. Search for the first true, last true, or any true by preserving an explicit answer range.", "The data need not be an array of values. You can binary-search the answer when feasibility changes only once, such as minimum shipping capacity.", "A sorted array with duplicates requires a chosen contract. 'Find target' and 'find first target' are different algorithms.", "let lo = 0, hi = n; // answer in [lo, hi)\nwhile (lo < hi) {\n  const mid = lo + Math.floor((hi - lo) / 2);\n  if (feasible(mid)) hi = mid; else lo = mid + 1;\n}\nreturn lo;"),
    lesson("sorting-as-preprocessing", "Sorting", "Intervals, duplicates, nearest neighbors, and greedy choices are hard to compare while values are in arbitrary order.", "Sort once in O(n log n), then scan with a local invariant. Merge intervals by comparing the next start to the current end; find duplicates by comparing neighbors; sweep events in chronological order.", "Sorting may destroy original order and index identity. Carry indices alongside values when the output needs original positions.", "A sorting step is not free, but it is often cheaper than trying to maintain global relationships through repeated nested scans.", "intervals.sort((a, b) => a[0] - b[0]);\nfor (const [start, end] of intervals) {\n  if (!merged.length || merged.at(-1)[1] < start) merged.push([start, end]);\n  else merged.at(-1)[1] = Math.max(merged.at(-1)[1], end);\n}"),
    lesson("divide-and-conquer", "Divide and Conquer", "A problem may look too large, but two independent halves may be easier to solve than the whole.", "Split into smaller subproblems, solve recursively, then combine. Merge sort combines two sorted halves in linear time, yielding T(n) = 2T(n/2) + O(n) = O(n log n).", "A divide is only useful if combination is controlled. Recombining every pair across halves can restore quadratic work.", "Keep the unit of progress clear: a midpoint must make both recursive ranges strictly smaller, especially with integer boundaries.", "function mergeSort(a) {\n  if (a.length <= 1) return a;\n  const mid = Math.floor(a.length / 2);\n  return merge(mergeSort(a.slice(0, mid)), mergeSort(a.slice(mid)));\n}"),
    lesson("backtracking", "Backtracking", "Some tasks require enumerating combinations, placements, or paths. There is no single greedy next choice that is always safe.", "Build a partial candidate, recurse on one choice, undo it, and try the next. Prune immediately when a partial candidate cannot lead to a valid answer.", "The worst-case tree is often exponential. Backtracking is appropriate only when constraints or pruning make that search viable.", "Undo exactly the state you changed. Shared mutable arrays cause bugs when a stored result is really a reference to later-mutated state.", "function choose(i, path) {\n  if (i === n) { answers.push([...path]); return; }\n  path.push(items[i]); choose(i + 1, path);\n  path.pop();          choose(i + 1, path);\n}"),
    lesson("greedy-and-exchange", "Greedy Algorithms", "Taking the locally best-looking choice feels efficient, but many problems punish a choice that blocks a better future.", "Use greedy when you can justify a greedy-choice property, often with an exchange argument: transform any optimal solution so it uses your first choice without making it worse.", "A counterexample is enough to invalidate a greedy rule. Coin change with arbitrary denominations is a classic trap.", "Sorting is often part of greedy, but sorted order alone is not proof. State what resource is consumed and why taking it now is safe.", "// activity selection: earliest finishing compatible interval\nintervals.sort((a, b) => a.end - b.end);\nfor (const x of intervals) if (x.start >= end) { take(x); end = x.end; }"),
    lesson("prefix-sums", "Prefix Sums", "If a program repeatedly asks for sums across intervals, rescanning every interval makes overlapping work expensive.", "Define prefix[0] = 0 and prefix[i + 1] = prefix[i] + a[i]. Then sum over [left, right] is prefix[right + 1] - prefix[left] in O(1) after O(n) preprocessing.", "Prefix sums are ideal for static data. If values change frequently, use a Fenwick tree or segment tree instead.", "The extra zero at prefix[0] eliminates the special case for ranges starting at index zero.", "const prefix = [0];\nfor (const x of a) prefix.push(prefix.at(-1) + x);\nconst rangeSum = (l, r) => prefix[r + 1] - prefix[l];"),
    lesson("intervals", "Intervals", "Meetings, ranges, and time spans look simple until two endpoints touch. Whether [1, 2] and [2, 3] overlap changes the answer.", "Sort by start time and maintain the active interval. Make the comparison match the contract: use next.start <= current.end for closed intervals, but next.start < current.end for half-open time blocks.", "One sorted scan solves merging and overlap detection, but room scheduling may require a min-heap of end times instead.", "Write interval conventions at the top of the solution. Most interval bugs are specification bugs disguised as comparison operators.", "closed:   [1────2] and [2────3] overlap\nhalf-open:[1────2) and [2────3) do not overlap"),
    lesson("bitwise-tools", "Bit Manipulation", "When values are small integers or symbols fit in a limited alphabet, general-purpose structures may carry unnecessary overhead.", "Use AND to test a bit, OR to add it, XOR to toggle or cancel pairs, and shifts to address positions. A bitmask can represent a subset in one machine word.", "Bit tricks are compact but easy to make unreadable. They are a poor choice when the domain exceeds the word size or clarity matters more than micro-optimization.", "XOR cancels equal values only under its exact algebraic assumptions. It does not find a unique value if several frequencies are irregular.", "const has = (mask, bit) => (mask & (1 << bit)) !== 0;\nconst add = (mask, bit) => mask | (1 << bit);")
  ]);

  window.SITE_CONTENT["graphs"] = track("5. Graphs & Connectivity", [
    lesson("modeling-a-graph", "Graph Representation", "The same story can be a grid, a dependency graph, an undirected friendship graph, or a weighted route map. The wrong model produces the wrong algorithm.", "Use an adjacency list for sparse graphs: O(V + E) space and neighbor iteration. Use an adjacency matrix when dense graphs need O(1) edge-existence checks. Decide whether edges are directed and weighted.", "An adjacency list does not give O(1) edge membership without extra structure. An adjacency matrix is prohibitive for huge sparse graphs.", "Build both directions for an undirected edge. Forgetting the reverse edge silently changes reachability.", "const graph = Array.from({ length: n }, () => []);\nfor (const [u, v] of edges) { graph[u].push(v); graph[v].push(u); }"),
    lesson("dfs-and-components", "Depth-First Search", "You need to know what can be reached, whether a region is connected, or whether a path exists. Trying every possible path separately duplicates work.", "Depth-first search marks a node, then recursively or iteratively visits each unvisited neighbor. Start a fresh DFS from each unseen node to count connected components.", "Recursive DFS can overflow on long paths. An explicit stack makes depth a heap allocation you can control.", "A visited set is not optional on cyclic graphs. Mark before exploring neighbors, otherwise two routes can recurse into each other forever.", "const stack = [start]; seen.add(start);\nwhile (stack.length) {\n  const u = stack.pop();\n  for (const v of graph[u]) if (!seen.has(v)) { seen.add(v); stack.push(v); }\n}"),
    lesson("bfs-shortest-unweighted", "Breadth-First Search", "In an unweighted graph, a shortest route is the route with the fewest edges, but DFS may find a much longer route first.", "Process nodes in FIFO layers. Store a distance when enqueuing, or run level-sized loops. The first visit to a node has the minimum number of edges from the start.", "This guarantee disappears when edge costs differ. Use Dijkstra for non-negative weights, not BFS with a wishful distance variable.", "To reconstruct a path, record parent[next] = current at discovery time, then follow parents backward from target.", "distance[start] = 0;\nqueue.push(start);\nfor (const next of graph[node]) if (distance[next] === -1) {\n  distance[next] = distance[node] + 1; queue.push(next);\n}"),
    lesson("topological-sort", "Topological Sort", "A build step must happen before another, but arbitrary graph traversal can output a dependent before its prerequisite.", "In Kahn's algorithm, compute indegrees, enqueue every zero-indegree node, and remove its outgoing edges. Every emitted node had no remaining prerequisite.", "A topological order exists only for a directed acyclic graph. Multiple valid orders are normal.", "If fewer than V nodes are emitted, do not return a partial order as success: the unprocessed nodes witness a cycle.", "for (const u of queue) {\n  order.push(u);\n  for (const v of graph[u]) if (--indegree[v] === 0) queue.push(v);\n}\nif (order.length !== n) throw new Error('cycle');"),
    lesson("dijkstra", "Dijkstra's Algorithm", "BFS fails when one edge costs 100 and another path uses two edges costing 1 each. You need the next cheapest tentative route, not the next discovered node.", "Keep tentative distances in a min-priority queue. When the smallest unprocessed distance is popped, it is final if all edge weights are non-negative; relax each outgoing edge.", "Negative edges destroy the settled-distance proof. Use Bellman-Ford when negative edges exist, and detect negative cycles when needed.", "A priority queue may contain stale entries after a better route is found. Skip an entry whose distance no longer equals dist[node].", "dist[start] = 0; push([0, start]);\nwhile (pq.size) {\n  const [d, u] = pq.pop(); if (d !== dist[u]) continue;\n  for (const [v, w] of graph[u]) if (d + w < dist[v]) {\n    dist[v] = d + w; push([dist[v], v]);\n  }\n}"),
    lesson("union-find", "Disjoint Set Union", "You receive many 'connect these two' and 'are these connected?' operations. Re-running DFS after each connection is too slow.", "Disjoint Set Union gives each component a representative. find(x) returns its root; union(a, b) merges roots. Path compression and union by size make long sequences nearly constant amortized time.", "Union-Find answers connectivity, not paths or component traversal. It cannot tell you the shortest route between two nodes.", "Always compare roots, not parent pointers directly: parents are implementation links, not necessarily final representatives.", "function find(x) {\n  if (parent[x] !== x) parent[x] = find(parent[x]);\n  return parent[x];\n}\nfunction union(a, b) { parent[find(a)] = find(b); }"),
    lesson("minimum-spanning-tree", "Minimum Spanning Tree", "You need a network that reaches every vertex with minimum total wire, road, or link cost; shortest paths from one source solve a different objective.", "Kruskal sorts edges and adds one if it joins two different components, using Union-Find to reject cycles. Prim grows one tree by repeatedly selecting its cheapest frontier edge.", "MST is defined for connected, weighted, undirected graphs. On disconnected input, the result is a minimum spanning forest.", "An MST does not preserve shortest paths between arbitrary pairs. Minimum total edge weight and minimum route distance are separate goals.", "edges.sort((a, b) => a.weight - b.weight);\nfor (const e of edges) if (find(e.u) !== find(e.v)) {\n  union(e.u, e.v); mst.push(e);\n}"),
    lesson("grid-as-a-graph", "Grid Graphs", "Island, maze, and matrix problems hide their nodes and edges inside row and column arithmetic.", "Treat each valid cell as a node and its permitted neighbors as edges. BFS gives minimum moves on uniform grids; DFS counts regions; multi-source BFS expands from every initial source simultaneously.", "Bounds checks and obstacle rules are part of the graph definition. Diagonal movement changes both degree and distance.", "Mark a cell visited when discovered. If mutation is allowed, changing the grid itself can replace a separate visited set.", "const dirs = [[1,0],[-1,0],[0,1],[0,-1]];\nfor (const [dr, dc] of dirs) {\n  const nr = r + dr, nc = c + dc;\n  if (0 <= nr && nr < rows && 0 <= nc && nc < cols) visit(nr, nc);\n}")
  ]);

  window.SITE_CONTENT["dynamic-programming"] = track("6. Dynamic Programming", [
    lesson("recognizing-dp", "Dynamic Programming", "A naive recursive solution may compute the same answer for the same input again and again. The recursion tree grows exponentially even when there are only O(n) distinct states.", "Use dynamic programming when subproblems overlap and an optimal answer can be built from optimal smaller answers. First write the recursive state; then cache it or fill it iteratively.", "Not every recursive problem is DP. If subproblems are independent, memoization may add memory without eliminating repeated work.", "The word 'optimal' is not enough. Define exactly what values make two subproblems equivalent; that definition is the state.", "fib(5)\n├─ fib(4) ─┐\n└─ fib(3) ─┼─ computed repeatedly without memoization\n            └─ same input ⇒ same cached answer"),
    lesson("state-transition-base", "DP State and Transition", "DP tables feel magical when they are written before the reasoning. Indexes then become a collection of unexplained special cases.", "For every DP problem answer four questions: what does dp[state] mean; what choices lead into it; what are its base states; and which state is the final answer? The recurrence follows from those meanings.", "A correct recurrence can still be too large: a two-dimensional state with n and m up to 10^5 is impossible even if each transition is O(1).", "Say the definition aloud, for example: dp[i] is the best value using the first i items. If that sentence is vague, the recurrence is not ready.", "// climbing stairs\ndp[0] = 1; dp[1] = 1;\nfor (let i = 2; i <= n; i++) dp[i] = dp[i - 1] + dp[i - 2];"),
    lesson("memoization-vs-tabulation", "Memoization and Tabulation", "You have a recurrence, but the order in which you evaluate states affects stack depth, memory layout, and which states are computed.", "Memoization follows the natural recursive demand and computes only reached states. Tabulation chooses an order where dependencies are already available, avoiding recursion overhead and often making space optimization clearer.", "Top-down can overflow the stack; bottom-up can fill states that are never needed. Neither is universally superior.", "Memoization needs a cache key that contains every varying parameter. Caching only i when the answer also depends on remaining capacity is silently wrong.", "// bottom-up: dependencies are earlier indices\nfor (let i = 1; i <= n; i++) {\n  dp[i] = bestTransitionFromEarlierStates(i);\n}"),
    lesson("knapsack-and-subset", "0/1 Knapsack", "You must choose items with tradeoffs: taking one consumes capacity and changes what can be taken later. A locally valuable item may not be globally best.", "For 0/1 knapsack, state is item prefix plus capacity. The transition compares skipping an item with taking it and using remaining capacity. Iterate capacity backward in a 1D table so an item is not reused.", "If each item may be used repeatedly, the recurrence is similar but the loop direction changes. That is the difference between 0/1 and unbounded knapsack.", "Backward versus forward iteration is not a coding detail: it determines whether the current item can read values it just wrote.", "for (const { weight, value } of items) {\n  for (let c = capacity; c >= weight; c--) {\n    dp[c] = Math.max(dp[c], dp[c - weight] + value);\n  }\n}"),
    lesson("sequence-dp", "Sequence Dynamic Programming", "Edit distance, longest common subsequence, and similar problems compare two ordered sequences. Choosing one character changes which prefixes remain.", "Let dp[i][j] describe the answer for prefixes of lengths i and j. If characters match, often extend a diagonal state; otherwise choose among states that drop one character from one prefix.", "The table has O(mn) cells, which is too expensive for very long strings. Some variants have specialized faster algorithms; others need a smaller constraint.", "Distinguish substring from subsequence. A subsequence may skip characters; a substring must stay contiguous.", "if (a[i - 1] === b[j - 1]) dp[i][j] = dp[i - 1][j - 1] + 1;\nelse dp[i][j] = Math.max(dp[i - 1][j], dp[i][j - 1]);"),
    lesson("lis-and-patience", "Longest Increasing Subsequence", "The longest increasing subsequence asks for ordered values that need not be adjacent. Checking every prior value gives a clear O(n²) DP.", "For each length, maintain the smallest possible tail value of an increasing subsequence of that length. Binary-search the first tail at least the new value and replace it, giving O(n log n).", "The tails array is not itself necessarily a valid answer sequence. Store predecessors and positions if reconstruction is required.", "Use lower_bound for strictly increasing LIS and upper_bound for non-decreasing variants; that one comparison changes duplicate handling.", "for (const x of nums) {\n  const i = lowerBound(tails, x);\n  tails[i] = x;\n}\nreturn tails.length;"),
    lesson("interval-dp", "Interval Dynamic Programming", "Some problems operate on a whole range: burst balloons, matrix-chain multiplication, or optimal parenthesization. The final action divides the remaining interval.", "Let dp[left][right] be the best answer for that interval. Try every possible final split k, combine already-solved smaller intervals, and fill ranges from short to long.", "There are O(n²) intervals and often O(n) split choices, yielding O(n³). This technique depends on small n.", "Do not fill arbitrary table order. An interval's transition reads shorter intervals, so length order is part of correctness.", "for (let len = 2; len <= n; len++)\n  for (let l = 0; l + len <= n; l++) {\n    const r = l + len - 1;\n    dp[l][r] = bestSplit(l, r);\n  }"),
    lesson("dp-space-optimization", "DP Space Optimization", "A correct table may use O(n²) memory even though each state reads only a previous row or a few prior positions.", "Inspect the transition's dependency window. Replace a full row with previous/current rows, or replace Fibonacci-style arrays with two variables. Preserve old values until every state that needs them has read them.", "Space optimization can make reconstruction impossible unless you store choices separately or rerun parts of the computation.", "Optimize space after the state definition is proven. A compact rolling array with unclear update order is harder to trust than a full table.", "let prev = 1, cur = 1;\nfor (let i = 2; i <= n; i++) {\n  [prev, cur] = [cur, prev + cur];\n}\nreturn cur;")
  ]);
})();
